// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:fdd176bc-a348-4802-8a21-1f007ee8725c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_BWLOmkh5J",
    "aws_user_pools_web_client_id": "8dro95t1nnrck0s9r5cllrgru",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5yv5obbypvgaxdswzcide2khoq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "vv2020siigo-vvsiigo",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
